{
	"OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/CreateEntitySuccessMessage.action",
	"Target": {
		"EntitySet": "ZZCamposAdicionales",
		"QueryOptions": "",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}