{
	"Headers": {
		"OfflineOData.TransactionID": "#Property:OrderId"
	},
	"Properties": {
		"AnomaliasStr": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_Anomalias.js",
		"AplicaNormaActualizar": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_ExcepNorma.js",
		"Celular": "{{#Property:oPages/#Property:pageTestForm1/#Property:txtCelular/#Property:value}}",
		"CobroCompartido": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_CobroCompartido.js",
		"DefectosStr": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_Defectos.js",
		"DestinoMedidor": "{{#Property:oPages/#Property:pageTestForm2/#Property:lstPickDestinosMedidor/#Property:value}}",
		"Email": "{{#Property:oPages/#Property:pageTestForm1/#Property:txtEmail/#Property:value}}",
		"EquipoSustituido": "{{#Property:oPages/#Property:pageTestForm2/#Property:lstPickMedidores/#Property:value}}",
		"EstatusUsuario": "{{#Property:sUserStatusChar}}",
		"FechaInicioEjecucion": "{{#Property:fInicio}}",
		"FechaLaboratorio": "{{#Property:oPages/#Property:pageTestForm2/#Property:dtPickFecLab/#Property:value}}",
		"HoraFinEjecucion": "{{#Property:hFin}}",
		"HoraInicioEjecucion": "{{#Property:hInicio}}",
		"IndiceOdoAnalitico": "{{#Property:oPages/#Property:pageTestForm3/#Property:IndiceOdoAnal/#Property:value}}",
		"IndiceOdoFisiologico": "{{#Property:oPages/#Property:pageTestForm3/#Property:IndiceOdoFisio/#Property:value}}",
		"LecturaControl": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_LecturaControl.js",
		"LecturaMedInstalado": "{{#Property:oPages/#Property:pageTestForm2/#Property:txtLectMedInstalado/#Property:value}}",
		"LecturaMedRetirado": "{{#Property:oPages/#Property:pageTestForm2/#Property:txtLectMedRetirado/#Property:value}}",
		"LecturaReconexion": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_LecturaReconexion.js",
		"LecturaSuspension": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_LecturaSuspencion.js",
		"MaterialEqInstalar": "{{#Property:oPages/#Property:pageTestForm2/#Property:txtMaterial/#Property:value}}",
		"MedidaPresion2": "{{#Property:oPages/#Property:pageTestForm3/#Property:UnidadPresAt/#Property:value}}",
		"MotivoSustitucion": "{{#Property:oPages/#Property:pageTestForm2/#Property:lstPickMotivosSustitucion/#Property:value}}",
		"NroSerieEqInstalar": "{{#Property:oPages/#Property:pageTestForm2/#Property:txtNumSerie/#Property:value}}",
		"NumeroCuotas": "{{#Property:oPages/#Property:pageTestForm1/#Property:txtCuotas/#Property:value}}",
		"PresionAtmosferica": "{{#Property:oPages/#Property:pageTestForm3/#Property:PresAtmo/#Property:value}}",
		"PresionRed": "{{#Property:oPages/#Property:pageTestForm3/#Property:PresRed/#Property:value}}",
		"TipoCorte": "{{#Property:oPages/#Property:pageTestForm1/#Property:lstPickTipoCorte/#Property:value}}",
		"Tula": "{{#Property:oPages/#Property:pageTestForm2/#Property:txPrecTula/#Property:value}}",
		"VacioInternoActualizar": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_VacioInterno.js",
		"Vinculo": "{{#Property:oPages/#Property:pageTestForm1/#Property:lstPickVinculo/#Property:value}}"
	},
	"Target": {
		"EntitySet": "ZZCamposAdicionales",
		"QueryOptions": "",
		"ReadLink": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_ReadLink.js",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}