{
	"Headers": {
		"OfflineOData.TransactionID": "#Property:OrderId"
	},
	"Properties": {
		"AnomaliasStr": "{{#Property:saveCamposAdicionales/#Property:AnomaliasStr}}",
		"AplicaNorma": "{{#Property:saveCamposAdicionales/#Property:AplicaNorma}}",
		"AplicaNormaActualizar": "{{#Property:saveCamposAdicionales/#Property:AplicaNormaActualizar}}",
		"CambioMedidor": "{{#Property:saveCamposAdicionales/#Property:CambioMedidor}}",
		"Celular": "{{#Property:saveCamposAdicionales/#Property:Celular}}",
		"CobroCompartido": "{{#Property:saveCamposAdicionales/#Property:CobroCompartido}}",
		"DefectosStr": "{{#Property:saveCamposAdicionales/#Property:DefectosStr}}",
		"DestinoMedidor": "{{#Property:saveCamposAdicionales/#Property:DestinoMedidor}}",
		"Email": "{{#Property:saveCamposAdicionales/#Property:Email}}",
		"EquipoSustituido": "{{#Property:saveCamposAdicionales/#Property:EquipoSustituido}}",
		"EstatusUsuario": "{{#Property:saveCamposAdicionales/#Property:EstatusUsuario}}",
		"FechaInicioEjecucion": "{{#Property:saveCamposAdicionales/#Property:FechaInicioEjecucion}}",
		"FechaLaboratorio": "{{#Property:saveCamposAdicionales/#Property:FechaLaboratorio}}",
		"HoraFinEjecucion": "{{#Property:saveCamposAdicionales/#Property:HoraFinEjecucion}}",
		"HoraInicioEjecucion": "{{#Property:saveCamposAdicionales/#Property:HoraInicioEjecucion}}",
		"IndiceOdoAnalitico": "{{#Property:saveCamposAdicionales/#Property:IndiceOdoAnalitico}}",
		"IndiceOdoFisiologico": "{{#Property:saveCamposAdicionales/#Property:IndiceOdoFisiologico}}",
		"LecturaControl": "{{#Property:saveCamposAdicionales/#Property:LecturaControl}}",
		"LecturaMedInstalado": "{{#Property:saveCamposAdicionales/#Property:LecturaMedInstalado}}",
		"LecturaMedRetirado": "{{#Property:saveCamposAdicionales/#Property:LecturaMedRetirado}}",
		"LecturaReconexion": "{{#Property:saveCamposAdicionales/#Property:LecturaReconexion}}",
		"LecturaSuspension": "{{#Property:saveCamposAdicionales/#Property:LecturaSuspension}}",
		"MaterialEqInstalar": "{{#Property:saveCamposAdicionales/#Property:MaterialEqInstalar}}",
		"MedidaPresion": "{{#Property:saveCamposAdicionales/#Property:MedidaPresion}}",
		"MedidaPresion2": "{{#Property:saveCamposAdicionales/#Property:MedidaPresion2}}",
		"MedidaPresionRed": "{{#Property:saveCamposAdicionales/#Property:MedidaPresionRed}}",
		"MedidorLaboratorio": "{{#Property:saveCamposAdicionales/#Property:MedidorLaboratorio}}",
		"MotivoSustitucion": "{{#Property:saveCamposAdicionales/#Property:MotivoSustitucion}}",
		"NroSerieEqInstalar": "{{#Property:saveCamposAdicionales/#Property:NroSerieEqInstalar}}",
		"NumeroCertificado": "{{#Property:saveCamposAdicionales/#Property:NumeroCertificado}}",
		"NumeroCuotas": "{{#Property:saveCamposAdicionales/#Property:NumeroCuotas}}",
		"PersonaAtVisita": "{{#Property:saveCamposAdicionales/#Property:PersonaAtVisita}}",
		"PresionAtmosferica": "{{#Property:saveCamposAdicionales/#Property:PresionAtmosferica}}",
		"PresionDinamica": "{{#Property:saveCamposAdicionales/#Property:PresionDinamica}}",
		"PresionEstatica": "{{#Property:saveCamposAdicionales/#Property:PresionEstatica}}",
		"PresionRed": "{{#Property:saveCamposAdicionales/#Property:PresionRed}}",
		"ServSuspendido": "{{#Property:saveCamposAdicionales/#Property:ServSuspendido}}",
		"SuspLineaMatriz": "{{#Property:saveCamposAdicionales/#Property:SuspLineaMatriz}}",
		"TipoCorte": "{{#Property:saveCamposAdicionales/#Property:TipoCorte}}",
		"Tula": "{{#Property:saveCamposAdicionales/#Property:Tula}}",
		"VacioInterno": "{{#Property:saveCamposAdicionales/#Property:VacioInterno}}",
		"VacioInternoActualizar": "{{#Property:saveCamposAdicionales/#Property:VacioInternoActualizar}}",
		"Vinculo": "{{#Property:saveCamposAdicionales/#Property:Vinculo}}"
	},
	"Target": {
		"EntitySet": "ZZCamposAdicionales",
		"QueryOptions": "",
		"ReadLink": "/SAPAssetManager/Rules/vanti/ZZCamposAdicionalesUpdate_ReadLink.js",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"_Type": "Action.Type.ODataService.UpdateEntity"
}