{
	"Target": {
		"EntitySet": "ZZHistEquipos",
		"ReadLink": "/SAPAssetManager/Rules/vanti/ZZHistEquiposDelete_ReadLink.js",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"_Type": "Action.Type.ODataService.DeleteEntity"
}