{
	"Animated": true,
	"Duration": 3,
	"IsIconHidden": true,
	"MaxNumberOfLines": 2,
	"Message": "/SAPAssetManager/Rules/WorkOrders/MobileStatus/WorkOrderMobileStatusSuccessMessage.js",
	"_Type": "Action.Type.ToastMessage"
}