{
	"Headers": {
		"OfflineOData.TransactionID": "#Control:Order/#Value"
	},
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
	"OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntitySuccessMessage.action",
	"Properties": {
		"ComponentDesc": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataComponentDesc.js",
		"ItemCategory": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataItemCategory.js",
		"ItemCategoryDesc": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataItemCategoryDesc.js",
		"MaterialNum": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataMaterialNum.js",
		"OperationDesc": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataOperationDesc.js",
		"OperationNo": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataOperationNo.js",
		"Plant": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataPlant.js",
		"RequirementQuantity": "#Control:QuantitySim/#Value",
		"TextTypeDesc": "#Control:TextItemSim/#Value",
		"UnitOfMeasure": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateSetOdataUnitOfMeasure.js"
	},
	"Target": {
		"EntitySet": "MyWorkOrderComponents",
		"ReadLink": "{@odata.readLink}",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"ValidationRule": "/SAPAssetManager/Rules/Parts/CreateUpdate/PartCreateUpdateValidation.js",
	"_Type": "Action.Type.ODataService.UpdateEntity"
}