{
	"OnFailure": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntityFailureMessage.action",
	"OnSuccess": "/SAPAssetManager/Actions/CreateUpdateDelete/UpdateEntitySuccessMessage.action",
	"Properties": {
		"EntryQuantity": "#Control:QuantitySim/#Value",
		"EntryUOM": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateEntryUOM.js",
		"MatDocItem": "",
		"Material": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateMaterial.js",
		"MovementType": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateMovementType.js",
		"OrderNumber": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateOrderNumber.js",
		"Plant": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdatePlant.js",
		"ReservationItemNumber": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateReservationItemNumber.js",
		"ReservationNumber": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateReservationNumber.js",
		"StorageLocation": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateStorageLocation.js"
	},
	"Target": {
		"EntitySet": "MaterialDocItems",
		"ReadLink": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueUpdateReadLink.js",
		"Service": "/SAPAssetManager/Services/AssetManager.service"
	},
	"ValidationRule": "/SAPAssetManager/Rules/Parts/Issue/CreateUpdate/PartIssueCreateUpdateValidation.js",
	"_Type": "Action.Type.ODataService.UpdateEntity"
}