{
	"Animated": true,
	"CompletionMessage": "$(L,sync_success)",
	"CompletionTimeout": 7,
	"Message": "$(L,sync_in_progress)",
	"OnSuccess": "/SAPAssetManager/Rules/ApplicationEvents/ApplicationOnSync.js",
	"ShowActivityIndicator": false,
	"_Type": "Action.Type.ProgressBanner"
}